language: generic

sudo: required

jobs:
  include:
    - script: wget -Nnv https://raw.githubusercontent.com/jeliasson/dockr/master/app/scripts/install.sh 2>&1 >/dev/null && bash install.sh
      name: Downloading install script

    - script: dockr
      name: Testing dockr command

    - script: dockr help
      name: Testing dockr help

    - script: dockr create test-app
      name: Create a dockr app

    - script: apt-get install docker.io git
      name: Install apt dependencies

    - script: dockr run
      name: Dockr run