version: "3.4"
services:
  dockr:
    image: node:10
    container_name: dockr
    restart: unless-stopped
    volumes:
      - "${DOCKR_PATH_CONFIG}/dockr/data:/data"
    ports:
      - "${DOCKR_PUID}:${DOCKR_PGID}"
    depends_on:
      - dockr-db

  dockr-db:
    image: mariadb
    container_name: dockr-db
    restart: unless-stopped
    user: ${PUID}:${PGID}
    environment:
      MYSQL_ROOT_PASSWORD: "${DOCKR_DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DOCKR_DB_DATABASE}"
      MYSQL_USER: "${DOCKR_DB_USER}"
      MYSQL_PASSWORD: "${DOCKR_DB_PASSWORD}"
    volumes:
      - "${DOCKR_PATH_CONFIG}/dockr-db/data/mysql:/var/lib/mysql"
    ports:
      - "53306:3306"