version: "3.7"
services:
  ${APP}-cli:
    container_name: ${APP}-cli
    hostname: ${APP}-cli
    image: node:10
    restart: unless-stopped
    volumes:
      - "${DATA_PATH}/cli:/data"

  ${APP}-web:
    container_name: ${APP}-web
    hostname: ${APP}-web
    image: node:10
    restart: unless-stopped
    volumes:
      - "${DATA_PATH}/web:/data"
    ports:
      - "8180:80"
    depends_on:
      - ${APP}-db

  ${APP}-db:
    container_name: ${APP}-db
    hostname: ${APP}-db
    image: mariadb
    restart: unless-stopped
    user: ${PUID}:${PGID}
    environment:
      TZ: "${TZ}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - "${DATA_PATH}/mysql:/var/lib/mysql"
    ports:
      - "${MYSQL_PORT}:3306"
